FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install gunicorn

COPY . .

EXPOSE 8050

CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:8050", "server:server"]